extend type Comment {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Comment", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Comment`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "Comment.user", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Comment`.`workout`. It must match the value of `Workout`.`id`. See `@ref` for how to customize it.
  """
  workoutId: UUID! @fdc_generated(from: "Comment.workout", purpose: IMPLICIT_REF_FIELD)
}
extend type Group {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Group", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Group`.`owner`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  ownerId: UUID! @fdc_generated(from: "Group.owner", purpose: IMPLICIT_REF_FIELD)
}
extend type Membership {
  """
  ✨ Implicit foreign key field based on `Membership`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "Membership.user", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Membership`.`group`. It must match the value of `Group`.`id`. See `@ref` for how to customize it.
  """
  groupId: UUID! @fdc_generated(from: "Membership.group", purpose: IMPLICIT_REF_FIELD)
}
extend type User {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "User", purpose: IMPLICIT_KEY_FIELD)
}
extend type Workout {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Workout", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Workout`.`group`. It must match the value of `Group`.`id`. See `@ref` for how to customize it.
  """
  groupId: UUID @fdc_generated(from: "Workout.group", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Workout`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "Workout.user", purpose: IMPLICIT_REF_FIELD)
}
